### ISSUE TITLE
Título se monta en gráfica en pantallas chicas

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ogp-montevideo#1]
![unknown](https://cloud.githubusercontent.com/assets/1755382/13203286/a16c3d8e-d893-11e5-935f-d70198443b9a.png)

**Comment by picandocodigo** [comment]
Ahí metí un poco de mano en el CSS para ésto y #2, pero habría que hacer un diseño responsive de pique.

**Comment by danielcarranza** [comment]
Quedó bárbaro.

**Comment by picandocodigo** [comment]
¿Cerramos éste issue?

**Comment by danielcarranza** [comment]
Oh yeah
