### ISSUE TITLE
Elemento amarillo se monta en texto de introducción y complica lectura

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ogp-montevideo#2]
![captura de pantalla 2016-02-21 a las 12 07 50 p m](https://cloud.githubusercontent.com/assets/1755382/13203297/c843c47c-d893-11e5-9e1d-7cb78dd7ee9b.png)

**Comment by picandocodigo** [comment]
¿Este también lo cerramos?

**Comment by danielcarranza** [comment]
Yup
